// <auto-generated />
using System;
using HappyBday.Persistence;
using HappyBday.Persistence.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HappyBday.Persistence.Migrations
{
    [DbContext(typeof(HappyBdayContext))]
    [Migration("20220128193701_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HappyBday.Domain.Aniversario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAniversario")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentecoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentescoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentescoId");

                    b.ToTable("Aniversarios");
                });

            modelBuilder.Entity("HappyBday.Domain.Parentesco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parentescos");
                });

            modelBuilder.Entity("HappyBday.Domain.Aniversario", b =>
                {
                    b.HasOne("HappyBday.Domain.Parentesco", "Parentesco")
                        .WithMany()
                        .HasForeignKey("ParentescoId");

                    b.Navigation("Parentesco");
                });
#pragma warning restore 612, 618
        }
    }
}
